// #define DEBUG

#define WM_ACCESSPOINT_PASSWORD "cynu4c9r"
#define MQTT_SERVER "homeassistant.lan"

// ESP-01
// GPIO_0
// TX = GPIO1 = LED
// GPIO_2
// RX = GPIO3

#define STEP_PIN 0
#define DIR_PIN 2

#define SOFTWARE_SERIAL_RX 5
#define SOFTWARE_SERIAL_TX 6

#define STEPPER_TMC2100
// #define STEPPER_A4988
// #define STEPPER_TMC2209

// A4988 Stepper
#if defined(STEPPER_A4988) || defined(STEPPER_TMC2100)
#define ENABLE_PIN 3
#endif

#ifdef STEPPER_A4988
#define STEPPER_ACCELERATION 800
#define STEPPER_MAXSPEED 400
#endif

#ifdef STEPPER_TMC2100
#define STEPPER_ACCELERATION 3000
#define STEPPER_MAXSPEED 10000
#endif

// TMC2209
#ifdef STEPPER_TMC2209
#define STEPPER_ACCELERATION 200
#define STEPPER_MAXSPEED 600
#endif

#define EEPROM_ADDRESS 0
#define EEPROM_SIZE 10